### ISSUE TITLE
N3FJP2Hamclock error

### ISSUE THREAD

**Issue by W1WH** [ChrisRomp/n3fjp2hamclock#12]
When I try to run N3FJP2Hamclock after connecting, I get the following error:

"Error calling hamClock API at http://localhost:8080: No connection could be made because the target machine actively refused it. (localhost:8080)"

Any advice on how I can fix this?

Thanks and 73,

Bill W1WH
wjhanrahan@gmail.com

**Comment by ChrisRomp** [comment]
Hi Bill @W1WH - The HamClock URL should be set to the URL where you access your HamClock. The `localhost` URL will only work if you're running HamClock on the same PC as N3FJP2HamClock.

So for example if you access your HamClock at `http://192.168.1.123:8080/live.html` you would enter `http://192.168.1.123:8080` in the HamClock URL field.  Please review the other configuration options in the [readme](https://github.com/ChrisRomp/n3fjp2hamclock/blob/main/README.md#running-n3fjp2hamclock).

**Comment by W1WH** [comment]
Thank you for the quick response and clarification Chris!  Got it running!

73 Bill W1WH
