### ISSUE TITLE
VE9XYZ Testing n3fjphamclock

### ISSUE THREAD

**Issue by ve9xyz** [ChrisRomp/n3fjp2hamclock#7]
Hi Chris:

I might be a good test candidate as I use the latest ACLog (v7.0.9), and have an Inovato-based Hamclock running v 3.01

I opened up the API option in AClog, and ran configured n3fjphamclock and ran a test callsign tab for L5YA and here was the display in your app:

Connected to N3FJP API server.
CallTab event received:
  Call: L5YA
  Lat: -34.8
  Lon: -65.9
Error calling hamClock API at http://localhost:8080: No connection could be made because the target machine actively refused it. (localhost:8080)

Looks like this is a Hamclock issue - possibly this is incompatible with the Inovato-based Hamclock product?

73

Kevin
VE9XYZ
Saint John, New Brunswick, CANADA
ve9xyz@hotmail.com

**Comment by ve9xyz** [comment]
My apologies Chris - I realized that I needed to point to the real Hamclock URL - replaced "localhost" with my Hamclock's IP and we're now functioning correctly.  

Works fine now - cool app!

73

Kevin

**Comment by ChrisRomp** [comment]
Glad to hear it!
